### ISSUE TITLE
CMD.EXE was started with the above path as the current directory. UNC paths are not supported.  Defaulting to Windows directory.

### ISSUE THREAD

**Issue by ghost** [SublimeText/WslBuild#3]
using last version of wsl and sublime text 3
![зображення](https://github.com/user-attachments/assets/fc634d10-dd51-455f-b104-7b133fddbdea)

**Comment by deathaxe** [comment]
What does the sublime-build file look like?

**Comment by deathaxe** [comment]
I can repreoduce the error message by opening a WSL path in ST and trying to execute a normal dosshell script in that path using a default build system.

1. from Windows calling `subl \\wsl.localhost\Ubuntu\home\...`
2. running build with following "cmd.sublime-build" file:

```
{
    "shell_cmd": "$file",
    "selector": "source.dosbatch"
}
```

`"shell_cmd"` always invokes default shell interpreter (CMD.exe on Windows) to execute given command line.

That's expected to fail as CMD.exe doesn't support running on UNC paths and is not how this package is designed to work.
